import { setTime } from "../../../utils/time";

export const notifications = [
    {
        type: 'comment',
        userImgUrl: '../../../../public/images/Image1md.png',
        userDisplayName: 'Domenica',
        userName: '@domenica',
        notificationTime: '1h',
        seen: false,
    },
    {
        type: 'like',
        userImgUrl: '../../../../public/images/Image2md.png',
        userDisplayName: 'Janice',
        userName: '@ethel',
        notificationTime: '2h',
        seen: false,
    },
    {
        type: 'shop',
        userImgUrl: '../../../../public/images/Image6md.png',
        userDisplayName: 'Janiya',
        userName: '@ethel2',
        notificationTime: '3h',
        seen: false,
    },
    {
        type: 'rating',
        userImgUrl: '../../../../public/images/Image4md.png',
        userDisplayName: 'Danial',
        userName: '@danial',
        notificationTime: '4h',
        seen: false,
    },
    {
        type: 'comment',
        userImgUrl: '../../../../public/images/imag5md.png',
        userDisplayName: 'Esmeralda',
        userName: '@esmeral',
        notificationTime: '5h',
        seen: false,
    },
    {
        type: 'comment',
        userImgUrl: '../../../../public/images/Image1md.png',
        userDisplayName: 'Domenica',
        userName: '@domenica',
        notificationTime: '1h',
        seen: false,
    },
    {
        type: 'like',
        userImgUrl: '../../../../public/images/Image2md.png',
        userDisplayName: 'Janice',
        userName: '@ethel',
        notificationTime: '2h',
        seen: false,
    },
    {
        type: 'shop',
        userImgUrl: '../../../../public/images/Image6md.png',
        userDisplayName: 'Janiya',
        userName: '@ethel2',
        notificationTime: '3h',
        seen: false,
    },
    {
        type: 'rating',
        userImgUrl: '../../../../public/images/Image4md.png',
        userDisplayName: 'Danial',
        userName: '@danial',
        notificationTime: '4h',
        seen: false,
    },
    {
        type: 'comment',
        userImgUrl: '../../../../public/images/imag5md.png',
        userDisplayName: 'Esmeralda',
        userName: '@esmeral',
        notificationTime: '5h',
        seen: false,
    },
]